[package]
name = "cc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
fs2 = "0.4"

[[bin]]
name = "compdb-cc"
path = "src/main.rs"

[[bin]]
name = "compdb-cxx"
path = "src/cxx.rs"
